name: Deploy
on: [push]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Generate docs
      run: npm run docs
    - name: Prepare gh-pages directory
      run: |
        export MAIN_REPO=$(pwd)
        mkdir ../gh-pages
        cd ../gh-pages
    - name: Checkout gh-pages branch
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Move docs
      run: |
        export DOCS_DIRECTORY=$(echo ${{ github.ref }} | cut -d / -f 3-)
        rm -rf $DOCS_DIRECTORY
        mv $MAIN_REPO/docs $DOCS_DIRECTORY
    - name: Push docs
      run: |
        git commit -am "Docs build for ${{ github.sha }}"
        git push
