name: Deploy
on: [push]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Generate docs
      run: npm run docs
    - name: Move docs
      run: |
        git clone -b origin/gh-pages . out
        export DOCS_DIRECTORY=$(echo ${{ github.ref }} | cut -d / -f 3-)
        rm -rf out/$DOCS_DIRECTORY
        mv docs out/$DOCS_DIRECTORY
    - name: Push docs
      run: |
        cd out
        git commit -am "Docs build for ${{ github.sha }}"
        git push
