name: Deploy
on: [push]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Generate docs
      run: |
        npm run docs
        git clone -b gh-pages . gh-pages
        export DOCS_DIRECTORY=$(echo ${{ github.ref }} | cut -d / -f 3-)
        rm -rf gh-pages/$DOCS_DIRECTORY
        mv -f docs gh-pages/$DOCS_DIRECTORY
        cd gh-pages
        git commit -am "Docs build for ${{ github.sha }}"
        git push
