name: Deploy
on: [push]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Generate docs
      run: |
        npm run docs
        REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        DOCS_DIRECTORY=$(echo ${{ github.ref }} | cut -d / -f 3- | sed -r 's/[\/\\]+/_/g')
        git clone -b gh-pages $REPO gh-pages
        rm -rf gh-pages/$DOCS_DIRECTORY
        mv -f docs gh-pages/$DOCS_DIRECTORY
        cd gh-pages
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -am "Docs build for ${{ github.sha }}"
        git push
