name: Deploy
on: [push]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - uses: spec-tacles/action-docs@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
